version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          cd docker
          docker build -t rt106-dev/rt106-simple-region-growing dev
      - run: |
          cd docker
          docker run rt106-dev/rt106-simple-region-growing > ops/rt106-simple-region-growing.tar.gz
      - run: |
          cd docker
          docker build -t rt106/rt106-simple-region-growing ops
