version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          cd docker
          docker build -t rt106-dev/rt106-simple-region-growing dev
      - run: |
          cd docker
          docker run rt106-dev/rt106-simple-region-growing > ops/rt106-simple-region-growing.tar.gz
      - run: |
          cd docker
          docker build -t rt106/rt106-simple-region-growing:0.1.$CIRCLE_BUILD_NUM ops
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker push rt106/rt106-simple-region-growing:0.1.$CIRCLE_BUILD_NUM
