version: 2
jobs:
  build:
    docker:
      - image: docker:17.12.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          cd docker
          docker build -t rt106-dev/rt106-simple-region-growing dev
      - run: |
          cd docker
          docker run rt106-dev/rt106-simple-region-growing > ops/rt106-simple-region-growing.tar.gz
      - run: |
          echo 'export DOCKER_TAG=$MAJOR.$MINOR.$PATCH-$CIRCLE_BUILD_NUM' >> $BASH_ENV
          source $BASH_ENV
          echo $DOCKER_TAG
      - run: |
          source $BASH_ENV
          cd docker
          docker build -t rt106/rt106-simple-region-growing:$DOCKER_TAG ops
      - deploy:
          command: |
            source $BASH_ENV
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker push rt106/rt106-simple-region-growing:$DOCKER_TAG
